version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rate-limiter:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RATE_LIMIT_WINDOW=10
      - RATE_LIMIT_MAX=5
